export const groupsTypes = {
    CREATE_POST: 'CREATE_POST',
    UPDATE_CITY: 'UPDATE_CITY',
    UPDATE_DISPLAY: 'UPDATE_DISPLAY',
    UPDATE_MSG_BOARD: 'UPDATE_MSG_BOARD',
    UPDATE_TAG: 'UPDATE_TAG'
}