export const groupsTypes = {
    MSG_SWITCH: 'MSG_SWITCH',
    SUBMIT_NEW_POST: 'SUBMIT_NEW_POST',
    UPDATE_CITY: 'UPDATE_CITY',
    UPDATE_DISPLAY: 'UPDATE_DISPLAY',
    UPDATE_MSG_BOARD: 'UPDATE_MSG_BOARD',
    UPDATE_NEW_POST: 'UPDATE_NEW_POST',
    UPDATE_TAG: 'UPDATE_TAG'
}