export const newGroupTypes = {
    UPDATE_DESCRIPTION: 'UPPDATE_DESCRIPTION',
    UPDATE_LOCATION: 'UPDATE_LOCATION',
    UPDATE_NEW_GROUP_OBJECT:'UPDATE_NEW_GROUP_OBJECT',
    UPDATE_STATUS: 'UPDATE_STATUS',
    UPDATE_TAG: 'UPDATE_TAG',
}